#!/bin/bash
export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$PATH

if [ ! -d apache-maven-3.3.9 ]; then
  wget http://www.eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  tar -zxf apache-maven-3.3.9-bin.tar.gz
fi

cd $OPENSHIFT_REPO_DIR

$OPENSHIFT_DATA_DIR/apache-maven-3.3.9/bin/mvn clean package -s .openshift/settings.xml -DskipTests=true
