#rabbitmq:
#  image: rabbitmq:management
#  ports:
#    - "5672:5672"
#    - "15672:15672"
MongoDB:
  image: mongo:latest
  ports:
    - "27017:27017"
  restart: always
redis:
  image: redis
  ports:
    - "6379:6379"
  restart: always
