spring:
      data:
          mongodb:
            uri: mongodb://localhost:27017/feeder

      mail:
          properties.mail.smtp.ssl.enable: true

mailConfig:
      defaultFrom:
      subject: New vacancy

logging:
      level.org.springframework: ERROR
      level.org.hibernate: ERROR
      level.org.apache.http: ERORR

security:
      ignored: /**
      basic:
          enabled: false


management:
      security:
          enabled: false

queue:
      use: false


push:
      use: true

job:
      cron: "0 0/10 * * * *"
      query: qa